name: Update ArcGIS Token

on:
  schedule:
    - cron: '*/30 * * * *' # Runs the script every 30 minutes
  push:
    paths:
      - 'GenerateToken.py'
      - 'index.html'

jobs:
  update-token:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you want to use

    - name: Install requests library
      run: pip install requests

    - name: Run GenerateToken script
      run: python GenerateToken.py

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and push changes
      run: |
        git status
        git add index.html
        git commit -m 'Update ArcGIS token' || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
